### ISSUE TITLE
Pojav issue probably 

### ISSUE THREAD

**Issue by Biggestmogger** [TempleDevelopment/Temple-Client#7]
When i disable stuff it crashes

**Comment by Biggestmogger** [comment]
> Really ? What stuff

Almost everything

**Comment by PhilipPanda** [comment]
It's a pojav issue, your playing on your phone expect stuff like this to happen.

**Comment by Biggestmogger** [comment]
> It's a pojav issue, your playing on your phone expect stuff like this to happen.
Do you have a fix?

**Comment by PhilipPanda** [comment]
Send us the crash log, we might be able to help.
